// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9OIkkBkTJlumdcQpZiZ2Dz3C53cVbBnQ',
    appId: '1:1030357716896:web:ce8ae8f51a1db0a82f5ec5',
    messagingSenderId: '1030357716896',
    projectId: 'tixe-backend',
    authDomain: 'tixe-backend.firebaseapp.com',
    storageBucket: 'tixe-backend.appspot.com',
    measurementId: 'G-WZ2FY94Y68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAgtsUY7YanxFtKrV9udZ6ihHLlpcV4bg',
    appId: '1:1030357716896:android:bc5138acb94b0d9b2f5ec5',
    messagingSenderId: '1030357716896',
    projectId: 'tixe-backend',
    storageBucket: 'tixe-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoi-fUNTlHKl2zcVDpuUVV7PHQm_r8vUI',
    appId: '1:1030357716896:ios:a1e82c02e8f6de872f5ec5',
    messagingSenderId: '1030357716896',
    projectId: 'tixe-backend',
    storageBucket: 'tixe-backend.appspot.com',
    iosBundleId: 'com.example.tixehr',
  );
}
